from PyQt5 import *
from PyQt5 import QtWidgets, QtCore, QtGui


class UIMainPage:

    def __init__(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 470, 664, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gantt_diagram_early = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gantt_diagram_early.sizePolicy().hasHeightForWidth())
        self.gantt_diagram_early.setSizePolicy(sizePolicy)
        self.gantt_diagram_early.setMinimumSize(QtCore.QSize(200, 60))
        self.gantt_diagram_early.setMaximumSize(QtCore.QSize(200, 60))
        self.gantt_diagram_early.setBaseSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.gantt_diagram_early.setFont(font)
        self.gantt_diagram_early.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gantt_diagram_early.setAutoFillBackground(False)
        self.gantt_diagram_early.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:0 rgba(100, 100, 100, 166), stop:1 rgba(255, 255, 255, 255));\n"
            "border-with: 10px;\n"
            "border-radius:10px;\n"
            "border-color: rgb(0, 0, 0);")
        self.gantt_diagram_early.setIconSize(QtCore.QSize(12, 12))
        self.gantt_diagram_early.setObjectName("gantt_diagram_early")
        self.gridLayout.addWidget(self.gantt_diagram_early, 0, 0, 1, 1)
        self.gantt_diagram_early_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gantt_diagram_early_2.sizePolicy().hasHeightForWidth())
        self.gantt_diagram_early_2.setSizePolicy(sizePolicy)
        self.gantt_diagram_early_2.setMinimumSize(QtCore.QSize(200, 60))
        self.gantt_diagram_early_2.setMaximumSize(QtCore.QSize(200, 60))
        self.gantt_diagram_early_2.setBaseSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.gantt_diagram_early_2.setFont(font)
        self.gantt_diagram_early_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gantt_diagram_early_2.setAutoFillBackground(False)
        self.gantt_diagram_early_2.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:0 rgba(100, 100, 100, 166), stop:1 rgba(255, 255, 255, 255));\n"
            "border-with: 10px;\n"
            "border-radius:10px;\n"
            "border-color: rgb(0, 0, 0);")
        self.gantt_diagram_early_2.setIconSize(QtCore.QSize(12, 12))
        self.gantt_diagram_early_2.setObjectName("gantt_diagram_early_2")
        self.gridLayout.addWidget(self.gantt_diagram_early_2, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(70, 30, 558, 180))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.factual_duration_text_5 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.factual_duration_text_5.sizePolicy().hasHeightForWidth())
        self.factual_duration_text_5.setSizePolicy(sizePolicy)
        self.factual_duration_text_5.setMinimumSize(QtCore.QSize(50, 0))
        self.factual_duration_text_5.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.factual_duration_text_5.setFont(font)
        self.factual_duration_text_5.setObjectName("factual_duration_text_5")
        self.gridLayout_4.addWidget(self.factual_duration_text_5, 1, 1, 1, 1)
        self.textEdit_9 = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_9.sizePolicy().hasHeightForWidth())
        self.textEdit_9.setSizePolicy(sizePolicy)
        self.textEdit_9.setMinimumSize(QtCore.QSize(250, 40))
        self.textEdit_9.setMaximumSize(QtCore.QSize(250, 40))
        self.textEdit_9.setObjectName("textEdit_9")
        self.gridLayout_4.addWidget(self.textEdit_9, 1, 5, 1, 1)
        self.textEdit_12 = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_12.sizePolicy().hasHeightForWidth())
        self.textEdit_12.setSizePolicy(sizePolicy)
        self.textEdit_12.setMinimumSize(QtCore.QSize(50, 40))
        self.textEdit_12.setMaximumSize(QtCore.QSize(50, 40))
        self.textEdit_12.setObjectName("textEdit_12")
        self.gridLayout_4.addWidget(self.textEdit_12, 2, 2, 1, 1)
        self.factual_duration_text_9 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.factual_duration_text_9.sizePolicy().hasHeightForWidth())
        self.factual_duration_text_9.setSizePolicy(sizePolicy)
        self.factual_duration_text_9.setMinimumSize(QtCore.QSize(50, 0))
        self.factual_duration_text_9.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.factual_duration_text_9.setFont(font)
        self.factual_duration_text_9.setObjectName("factual_duration_text_9")
        self.gridLayout_4.addWidget(self.factual_duration_text_9, 1, 4, 1, 1)
        self.factual_duration_text_6 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.factual_duration_text_6.sizePolicy().hasHeightForWidth())
        self.factual_duration_text_6.setSizePolicy(sizePolicy)
        self.factual_duration_text_6.setMinimumSize(QtCore.QSize(50, 0))
        self.factual_duration_text_6.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.factual_duration_text_6.setFont(font)
        self.factual_duration_text_6.setObjectName("factual_duration_text_6")
        self.gridLayout_4.addWidget(self.factual_duration_text_6, 2, 1, 1, 1)
        self.textEdit_8 = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_8.sizePolicy().hasHeightForWidth())
        self.textEdit_8.setSizePolicy(sizePolicy)
        self.textEdit_8.setMinimumSize(QtCore.QSize(250, 40))
        self.textEdit_8.setMaximumSize(QtCore.QSize(250, 40))
        self.textEdit_8.setObjectName("textEdit_8")
        self.gridLayout_4.addWidget(self.textEdit_8, 0, 5, 1, 1)
        self.factual_duration_text_8 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.factual_duration_text_8.sizePolicy().hasHeightForWidth())
        self.factual_duration_text_8.setSizePolicy(sizePolicy)
        self.factual_duration_text_8.setMinimumSize(QtCore.QSize(50, 0))
        self.factual_duration_text_8.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.factual_duration_text_8.setFont(font)
        self.factual_duration_text_8.setObjectName("factual_duration_text_8")
        self.gridLayout_4.addWidget(self.factual_duration_text_8, 0, 4, 1, 1)
        self.textEdit_11 = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_11.sizePolicy().hasHeightForWidth())
        self.textEdit_11.setSizePolicy(sizePolicy)
        self.textEdit_11.setMinimumSize(QtCore.QSize(50, 40))
        self.textEdit_11.setMaximumSize(QtCore.QSize(50, 40))
        self.textEdit_11.setObjectName("textEdit_11")
        self.gridLayout_4.addWidget(self.textEdit_11, 1, 2, 1, 1)
        self.factual_duration_text_7 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.factual_duration_text_7.sizePolicy().hasHeightForWidth())
        self.factual_duration_text_7.setSizePolicy(sizePolicy)
        self.factual_duration_text_7.setMinimumSize(QtCore.QSize(50, 0))
        self.factual_duration_text_7.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.factual_duration_text_7.setFont(font)
        self.factual_duration_text_7.setObjectName("factual_duration_text_7")
        self.gridLayout_4.addWidget(self.factual_duration_text_7, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 0, 1, 1)
        self.factual_duration_text_10 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.factual_duration_text_10.sizePolicy().hasHeightForWidth())
        self.factual_duration_text_10.setSizePolicy(sizePolicy)
        self.factual_duration_text_10.setMinimumSize(QtCore.QSize(50, 0))
        self.factual_duration_text_10.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.factual_duration_text_10.setFont(font)
        self.factual_duration_text_10.setObjectName("factual_duration_text_10")
        self.gridLayout_4.addWidget(self.factual_duration_text_10, 2, 4, 1, 1)
        self.textEdit_13 = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_13.sizePolicy().hasHeightForWidth())
        self.textEdit_13.setSizePolicy(sizePolicy)
        self.textEdit_13.setMinimumSize(QtCore.QSize(50, 40))
        self.textEdit_13.setMaximumSize(QtCore.QSize(50, 40))
        self.textEdit_13.setObjectName("textEdit_13")
        self.gridLayout_4.addWidget(self.textEdit_13, 3, 2, 1, 1)
        self.textEdit_10 = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_10.sizePolicy().hasHeightForWidth())
        self.textEdit_10.setSizePolicy(sizePolicy)
        self.textEdit_10.setMinimumSize(QtCore.QSize(50, 40))
        self.textEdit_10.setMaximumSize(QtCore.QSize(50, 40))
        self.textEdit_10.setObjectName("textEdit_10")
        self.gridLayout_4.addWidget(self.textEdit_10, 0, 2, 1, 1)
        self.textEdit_14 = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_14.sizePolicy().hasHeightForWidth())
        self.textEdit_14.setSizePolicy(sizePolicy)
        self.textEdit_14.setMinimumSize(QtCore.QSize(50, 40))
        self.textEdit_14.setMaximumSize(QtCore.QSize(50, 40))
        self.textEdit_14.setObjectName("textEdit_14")
        self.gridLayout_4.addWidget(self.textEdit_14, 2, 5, 1, 1)
        self.factual_duration_text_4 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.factual_duration_text_4.sizePolicy().hasHeightForWidth())
        self.factual_duration_text_4.setSizePolicy(sizePolicy)
        self.factual_duration_text_4.setMinimumSize(QtCore.QSize(50, 0))
        self.factual_duration_text_4.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.factual_duration_text_4.setFont(font)
        self.factual_duration_text_4.setObjectName("factual_duration_text_4")
        self.gridLayout_4.addWidget(self.factual_duration_text_4, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 6, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(70, 230, 410, 226))
        self.widget1.setObjectName("widget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 0, 1, 1)
        self.factual_duration_text_2 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.factual_duration_text_2.sizePolicy().hasHeightForWidth())
        self.factual_duration_text_2.setSizePolicy(sizePolicy)
        self.factual_duration_text_2.setMinimumSize(QtCore.QSize(100, 0))
        self.factual_duration_text_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.factual_duration_text_2.setFont(font)
        self.factual_duration_text_2.setObjectName("factual_duration_text_2")
        self.gridLayout_3.addWidget(self.factual_duration_text_2, 3, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_3.addItem(spacerItem5, 1, 2, 1, 1)
        self.textEdit_6 = QtWidgets.QTextEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_6.sizePolicy().hasHeightForWidth())
        self.textEdit_6.setSizePolicy(sizePolicy)
        self.textEdit_6.setMinimumSize(QtCore.QSize(250, 40))
        self.textEdit_6.setMaximumSize(QtCore.QSize(250, 40))
        self.textEdit_6.setObjectName("textEdit_6")
        self.gridLayout_3.addWidget(self.textEdit_6, 3, 2, 1, 1)
        self.textEdit_7 = QtWidgets.QTextEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_7.sizePolicy().hasHeightForWidth())
        self.textEdit_7.setSizePolicy(sizePolicy)
        self.textEdit_7.setMinimumSize(QtCore.QSize(250, 40))
        self.textEdit_7.setMaximumSize(QtCore.QSize(250, 40))
        self.textEdit_7.setObjectName("textEdit_7")
        self.gridLayout_3.addWidget(self.textEdit_7, 4, 2, 1, 1)
        self.textEdit_5 = QtWidgets.QTextEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_5.sizePolicy().hasHeightForWidth())
        self.textEdit_5.setSizePolicy(sizePolicy)
        self.textEdit_5.setMinimumSize(QtCore.QSize(250, 40))
        self.textEdit_5.setMaximumSize(QtCore.QSize(250, 40))
        self.textEdit_5.setObjectName("textEdit_5")
        self.gridLayout_3.addWidget(self.textEdit_5, 2, 2, 1, 1)
        self.factual_duration_text = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.factual_duration_text.sizePolicy().hasHeightForWidth())
        self.factual_duration_text.setSizePolicy(sizePolicy)
        self.factual_duration_text.setMinimumSize(QtCore.QSize(100, 0))
        self.factual_duration_text.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.factual_duration_text.setFont(font)
        self.factual_duration_text.setObjectName("factual_duration_text")
        self.gridLayout_3.addWidget(self.factual_duration_text, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(35, 40, QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_3.addItem(spacerItem6, 5, 2, 1, 1)
        self.factual_duration_text_3 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.factual_duration_text_3.sizePolicy().hasHeightForWidth())
        self.factual_duration_text_3.setSizePolicy(sizePolicy)
        self.factual_duration_text_3.setMinimumSize(QtCore.QSize(100, 0))
        self.factual_duration_text_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.factual_duration_text_3.setFont(font)
        self.factual_duration_text_3.setObjectName("factual_duration_text_3")
        self.gridLayout_3.addWidget(self.factual_duration_text_3, 4, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gantt_diagram_early.setText(_translate("MainWindow", "Ввести значения"))
        self.gantt_diagram_early_2.setText(_translate("MainWindow", "Построить график"))
        self.factual_duration_text_5.setText(_translate("MainWindow", "Ny"))
        self.factual_duration_text_9.setText(_translate("MainWindow", "hy"))
        self.factual_duration_text_6.setText(_translate("MainWindow", "x0"))
        self.factual_duration_text_8.setText(_translate("MainWindow", "hx"))
        self.factual_duration_text_7.setText(_translate("MainWindow", "y0"))
        self.factual_duration_text_10.setText(_translate("MainWindow", "t"))
        self.factual_duration_text_4.setText(_translate("MainWindow", "Nx"))
        self.factual_duration_text_2.setText(_translate("MainWindow", "Phi(x,y)"))
        self.factual_duration_text.setText(_translate("MainWindow", "f(x,y,t)"))
        self.factual_duration_text_3.setText(_translate("MainWindow", "Psi(x,y,t)"))


